name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    # Weekly: Wednesday 7:00am PST (15:00 UTC).
    - cron: "0 15 * * 3"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}

jobs:
  linux:
    name: Build from Linux
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      - uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}-linux
          repository-cache: true
      - run: bazel build --config=buildbuddy ${BUILDBUDDY_API_KEY:+--remote_header=x-buildbuddy-api-key=$BUILDBUDDY_API_KEY} //...
